// flow-typed signature: 1ff183a1a318c346ae12cf2c0849197c
// flow-typed version: <<STUB>>/countdown_v^2.6.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'countdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'countdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'countdown/countdown' {
  declare module.exports: any;
}

// Filename aliases
declare module 'countdown/countdown.js' {
  declare module.exports: $Exports<'countdown/countdown'>;
}
