// flow-typed signature: 23dc750f7903ba5046eb7db13ecb3d9b
// flow-typed version: <<STUB>>/web-switch-client_vhttps://github.com/ChazZeromus/web-switch-client.git/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'web-switch-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'web-switch-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'web-switch-client/flow-typed/npm/@babel/cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'web-switch-client/flow-typed/npm/@babel/core_vx.x.x' {
  declare module.exports: any;
}

declare module 'web-switch-client/flow-typed/npm/@babel/node_vx.x.x' {
  declare module.exports: any;
}

declare module 'web-switch-client/flow-typed/npm/@babel/plugin-proposal-class-properties_vx.x.x' {
  declare module.exports: any;
}

declare module 'web-switch-client/flow-typed/npm/@babel/preset-env_vx.x.x' {
  declare module.exports: any;
}

declare module 'web-switch-client/flow-typed/npm/@babel/preset-flow_vx.x.x' {
  declare module.exports: any;
}

declare module 'web-switch-client/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module 'web-switch-client/flow-typed/npm/babel-jest_vx.x.x' {
  declare module.exports: any;
}

declare module 'web-switch-client/flow-typed/npm/event-emitter-es6_vx.x.x' {
  declare module.exports: any;
}

declare module 'web-switch-client/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'web-switch-client/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module 'web-switch-client/flow-typed/npm/jest_v23.x.x' {
  declare module.exports: any;
}

declare module 'web-switch-client/flow-typed/npm/lodash_v4.x.x' {
  declare module.exports: any;
}

declare module 'web-switch-client/flow-typed/npm/monotonic-timestamp_vx.x.x' {
  declare module.exports: any;
}

declare module 'web-switch-client/flow-typed/npm/uuid_v3.x.x' {
  declare module.exports: any;
}

declare module 'web-switch-client/flow-typed/npm/ws_vx.x.x' {
  declare module.exports: any;
}

declare module 'web-switch-client/src/client' {
  declare module.exports: any;
}

declare module 'web-switch-client/src/client.test' {
  declare module.exports: any;
}

declare module 'web-switch-client/src/connect_test' {
  declare module.exports: any;
}

declare module 'web-switch-client/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'web-switch-client/flow-typed/npm/@babel/cli_vx.x.x.js' {
  declare module.exports: $Exports<'web-switch-client/flow-typed/npm/@babel/cli_vx.x.x'>;
}
declare module 'web-switch-client/flow-typed/npm/@babel/core_vx.x.x.js' {
  declare module.exports: $Exports<'web-switch-client/flow-typed/npm/@babel/core_vx.x.x'>;
}
declare module 'web-switch-client/flow-typed/npm/@babel/node_vx.x.x.js' {
  declare module.exports: $Exports<'web-switch-client/flow-typed/npm/@babel/node_vx.x.x'>;
}
declare module 'web-switch-client/flow-typed/npm/@babel/plugin-proposal-class-properties_vx.x.x.js' {
  declare module.exports: $Exports<'web-switch-client/flow-typed/npm/@babel/plugin-proposal-class-properties_vx.x.x'>;
}
declare module 'web-switch-client/flow-typed/npm/@babel/preset-env_vx.x.x.js' {
  declare module.exports: $Exports<'web-switch-client/flow-typed/npm/@babel/preset-env_vx.x.x'>;
}
declare module 'web-switch-client/flow-typed/npm/@babel/preset-flow_vx.x.x.js' {
  declare module.exports: $Exports<'web-switch-client/flow-typed/npm/@babel/preset-flow_vx.x.x'>;
}
declare module 'web-switch-client/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<'web-switch-client/flow-typed/npm/babel-core_vx.x.x'>;
}
declare module 'web-switch-client/flow-typed/npm/babel-jest_vx.x.x.js' {
  declare module.exports: $Exports<'web-switch-client/flow-typed/npm/babel-jest_vx.x.x'>;
}
declare module 'web-switch-client/flow-typed/npm/event-emitter-es6_vx.x.x.js' {
  declare module.exports: $Exports<'web-switch-client/flow-typed/npm/event-emitter-es6_vx.x.x'>;
}
declare module 'web-switch-client/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'web-switch-client/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'web-switch-client/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'web-switch-client/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module 'web-switch-client/flow-typed/npm/jest_v23.x.x.js' {
  declare module.exports: $Exports<'web-switch-client/flow-typed/npm/jest_v23.x.x'>;
}
declare module 'web-switch-client/flow-typed/npm/lodash_v4.x.x.js' {
  declare module.exports: $Exports<'web-switch-client/flow-typed/npm/lodash_v4.x.x'>;
}
declare module 'web-switch-client/flow-typed/npm/monotonic-timestamp_vx.x.x.js' {
  declare module.exports: $Exports<'web-switch-client/flow-typed/npm/monotonic-timestamp_vx.x.x'>;
}
declare module 'web-switch-client/flow-typed/npm/uuid_v3.x.x.js' {
  declare module.exports: $Exports<'web-switch-client/flow-typed/npm/uuid_v3.x.x'>;
}
declare module 'web-switch-client/flow-typed/npm/ws_vx.x.x.js' {
  declare module.exports: $Exports<'web-switch-client/flow-typed/npm/ws_vx.x.x'>;
}
declare module 'web-switch-client/src/client.js' {
  declare module.exports: $Exports<'web-switch-client/src/client'>;
}
declare module 'web-switch-client/src/client.test.js' {
  declare module.exports: $Exports<'web-switch-client/src/client.test'>;
}
declare module 'web-switch-client/src/connect_test.js' {
  declare module.exports: $Exports<'web-switch-client/src/connect_test'>;
}
declare module 'web-switch-client/src/utils.js' {
  declare module.exports: $Exports<'web-switch-client/src/utils'>;
}
